### ISSUE TITLE
Create  textfields for  calculation and answer on the top part

### ISSUE THREAD

**Issue by SHREYANSH-AGRAWAL0** [SHREYANSH-AGRAWAL0/calculator-flutter#1]

**Comment by codexaditi** [comment]
According to me the code is ---->
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: calculator());
  }
}

class calculator extends StatelessWidget {
  const calculator({super.key});

  @override
  Widget build(BuildContext context) {
    return const Material(
        child: Column(
      children: [Text('Calculation'), Text('Answer')],
    ));
  }
}

**Comment by SHREYANSH-AGRAWAL0** [comment]
@codexaditi 
Yes, what you have written is correct. 
You do not have to paste the code here. 
Follow these steps for the submission 
- Fork the repository
- clone the repository
- create a new branch from the current working branch ie. develop 
- add your code and make a new commit 
- push your code on your forked repo
- create a pull request on the main repo and link the branch to the issue

Now I am assigning this issue to you. 
Complete these steps to make your contribution

Also I have specified the area on the code where you have to add your code.

**Comment by SHREYANSH-AGRAWAL0** [comment]
#6 
was the PR for this issue 
Issue has been resolved

**Comment by SHREYANSH-AGRAWAL0** [comment]
DM me on whatsapp.
